# backend_django_setup/Dockerfile

FROM python:3.13

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Dependências do sistema
RUN apt-get update && apt-get install -y build-essential libpq-dev ffmpeg && rm -rf /var/lib/apt/lists/*

# Diretório de trabalho
WORKDIR /app

# Instalar dependências do projeto
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copiar projeto
COPY . .

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
